services:
  ready: # stub service to ensure compose up waits until rabbitmq is healthy
    image: "busybox"
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: wagslane
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
